### ISSUE TITLE
[Idea] Origins Plugin

### ISSUE THREAD

**Issue by SpyC0der77** [NerdyPuzzle/MCreator-plugin-builder#1]
It would be really cool if there was an origins plugin for mcreator, where you could create your own origins, and maybe even origin classes. I would definitely use that a ton.

**Comment by NerdyPuzzle** [comment]
This is not a suggestions page, this is an issue page for the geckolib plugin.

**Comment by SpyC0der77** [comment]
Where do I put suggestions?

**Comment by SpyC0der77** [comment]
?
