### ISSUE TITLE
Mod Elements not generating Java code.

### ISSUE THREAD

**Issue by jcm236** [NerdyPuzzle/MCreator-plugin-builder#3]
I am making a plugin that uses the mod elements feature in the plugin builder. I made the mod elements and built the project but there is no java code generated in the javacode directory. I am using release 1.8 on the plugin builder on linux (Ubuntu 22.04) using [Wine](https://www.winehq.org/).

Thank You in advance.

**Comment by jcm236** [comment]
@NerdyPuzzle Please respond.

**Comment by NerdyPuzzle** [comment]
Currently mod elements are a mess and I plan to rework them in the future. I recommend not using them and manually coding the plugin instead if you want to add a mod element to MCreator.

**Comment by jcm236** [comment]
I tried to do this but build.gradle keeps throwing errors. Could you explain how I should setup the project in intellij idea community edition?

**Comment by jcm236** [comment]
I set mcreator_path in gradle.properties to the path of my mcreator installation.
It keeps telling me that it does not have a configuration with the name of implementation. The project i used is the DemoJavaPlugin example.

**Comment by NerdyPuzzle** [comment]
This is not the place for help with intellij

**Comment by jcm236** [comment]
Actually i scrapped gradle. Im building my plugin the way the PluginBuilder does. So thanks for that idea.

**Comment by NerdyPuzzle** [comment]
You can do it without gradle like plugin builder, it's just more convenient with it.
